### ISSUE TITLE
navigation.side.hide feature leaves an empty space on the side

### ISSUE THREAD

**Issue by ntno** [ntno/mkdocs-terminal#129]
Using navigation.side.hide feature leaves an empty space on the side. Would be nice to get rid of it.

_Originally posted by @jpasikainen in https://github.com/ntno/mkdocs-terminal/issues/21#issuecomment-1492078861_
           

Hello @jpasikainen 
Can you please take a look at the following screenshots and let me know if this is the expected behavior of your suggestion?

## before 
`navigation.side.hide` is enabled but main content is to the right of the "Terminal for MkDocs" site title:
<br>
<img width="1000" alt="with-side-nav-hide" src="https://user-images.githubusercontent.com/20992605/232176958-3bfc48fc-cb48-47ff-bff3-325db27a9f4d.png">

## proposed change
when `navigation.side.hide` is enabled, main content should begin directly beneath the "Terminal for MkDocs" site title:
<br>
<img width="1000" alt="proposed-change" src="https://user-images.githubusercontent.com/20992605/232176963-dba91688-db6b-4748-a5f5-7ad689d6eae5.png">

**Comment by ntno** [comment]
hi @jpasikainen 
please check out the screenshots on this PR and let me know what you think: https://github.com/ntno/mkdocs-terminal/pull/130
thanks for the suggestion!

**Comment by jpasikainen** [comment]
> hi @jpasikainen 
> please check out the screenshots on this PR and let me know what you think: https://github.com/ntno/mkdocs-terminal/pull/130
> thanks for the suggestion!  

Yeah this is exactly what I meant. Looks good!

**Comment by ntno** [comment]
great!  published change in version 4.4.0
